### ISSUE TITLE
Installing vtcl on Linux

### ISSUE THREAD

**Issue by circuitikzuser** [hpheidinger/vtcl.vtcl-8.6#4]
After extracting latest source, I run ./configure.
Configure does nothing and doesnt create a make file.
make install obviously cannot work.

It seems impossible to install vtcl on Linux with the sources as is.
There is also no Installation instructions in the sources.
The readme contains nothing but changelogs.

How do I install this ?

After following 
http://vtcl.sourceforge.net/?x=doc_install
I get
```
# ./vtcl
Error in startup script: couldn't open "/usr/local/vtcl/images/title.gif": no such file or directory
    while executing
"image create photo "title"  -file [file join $vTcl(VTCL_HOME) images title.gif]"
    (procedure "vTcl:splash" line 7)
    invoked from within
"vTcl:splash"
    (procedure "vTcl:setup" line 69)
    invoked from within
"vTcl:setup"
    (procedure "vTcl:main" line 43)
    invoked from within
"vTcl:main $argc $argv"
    (file "/usr/local/vtcl/vtcl.tcl" line 790)

```
So there are missing folders in the source..

**Comment by hpheidinger** [comment]
There is nothing to 'compile'. Vtcl is a TCL-GUI written in TCL and so it is pretty self-content.
The 'configure' script does nothing but looking for your TCL environment on your individual computer and creates the Vtcl 'bootup script' for the environment that you have established.

Do as 'root' ...

cd /usr/local
git clone https://github.com/hpheidinger/vtcl.vtcl-8.6.git
ln -sf vtcl.vtcl-8.6 vtcl-8.6
cd vtcl-8.6
./configure
cd /usr/local/bin/
ln -sf ../vtcl-8.6/vtcl vtcl

(You can cut-and-paste above lines in a terminal window and I have just
checked this with my notebook running Fedora-29)

Assure you have /usr/local/bin in your search path ($PATH)
Then just start 'vtcl' from a console or make yourself a starter icon
for the desktop that you use (Gnome. MATE, XFCE, KDE, etc ...) to call
/usr/local/bin/vtcl


Best regards ...

**Comment by circuitikzuser** [comment]
It worked thanks.
Why not have that in an install script. ?
I couldnt figure it out at all, but the solution was simple.



Would have been nice if there was a default simple example that installs with vtcl at default.
This is most likely the official manual right ?
http://vtcl.sourceforge.net/tutorial.html

I am not new to TCL/TK but new to vtcl. 

Really great, I created an application in 10 minutes flat.!

Thanks a lot.

**Comment by circuitikzuser** [comment]
Last questions. 

1) I created a new application and finished it.
But next time I started VTCL the Widget menu was completely gone and I annot get it back again to do the next app.
2) There is seemingly no way from within vtcl to remove the New TopLevel-1 Alias. Sure I can edit it in the code, but it should not be necessary. Where do I edit it in vtcl.

Thanks thats all

**Comment by circuitikzuser** [comment]
The vtcl forum on github seems completely dead.
Is there another more active forum you are aware of.

Last questions.
I created a new application and finished it.
But next time I started VTCL the Widget menu was completely gone and I cannot get it back again to do the next app. Why did it disappear and more importantly, how do I get it back ?
There is seemingly no way from within vtcl to remove the New TopLevel-1 Alias. Sure I can edit it in the code, but it should not be necessary. Where do I edit it in vtcl.

Thanks

**Comment by hpheidinger** [comment]
First things first ...
Forget about the stuff that you will find on SourceForge. This repository was orphaned by former maintainers in 2007 at Vtcl release 1.6.1a at TCL/TK 8.4 and did not work with TCL/TK 8.5 anymore. Rildo Pragana (Brazil) provided a hack in 2010 to get it working again. but with TCK/TK 8.6 it was failing again.
Since VTCL by the idea of Steward Allen to have a TCL/TK-IDE written in vanilla TCL/TK itself was a gorgeous thing and I liked it very much ... it worked perfectly to develop rapid GUIs for any purpose. 
For a project I brushed-up VTCL  in 2016 to have it work with TCL/TK-8.6 again and lifted the version number from 1.6 to 8.6 to have that in sync with the TCL/TK release.
Looking deeper into it I found that former maintainers have integrated BWidgets 1.3 as VTCLs basis; i.e.  kind of 'hard-coded' into VTCL - which was an evil decision because newer BWidgets (state is 1.9 nowadays or even newer). As a consequence loading a newer BWidgets package will break the whole thing.
It is a tremendous work and code rewrite of about 1 year to do in order to hide the BWidgets-1.3 as something like 'VTwidgets' that VTCL essentially needs. I have a business (actually two) to manage and cannot spend that much time to brush-up VTCL to a state that has a future for further development. But you may create a fund-raiser and gather 200.000 Euros to make me change my mind ... since my existence has precedence ...

**Comment by hpheidinger** [comment]
I cannot relate to the "Widget menu was completely gone" thing.
The "Widget toolbar" cannot even be closed. 
You get an error message: 'The tool bar cannot be closed' ... if you try to do so.
If you click on 'Toplevel' in the  'Widget toolbar' (on the left) you get a new top-level window
but it is really, really minimalistic not to say tiny ... just stretch it to your needs ...
Having a "Widget tree" window open helps.

Best regards ...
